### ISSUE TITLE
answer to question from IRC

### ISSUE THREAD

**Issue by ammen99** [Javyre/swayfire#1]
Hi, I just saw your question on IRC but you've disconnected :)

> I'm having some trouble implementing interactive resizing using the mouse. The views seem to lag behind when their geometry is set it doesnt apply it right away and so getting their geometry with get_wm_geometry is unreliable as well
> using set_resizing only solves this lag in a few simple cases where only a single view is being resized, but it still happens when resizing multiple views at the same time when theyre tiled together

The problem is the following: Wayfire does not resize the views directly. Instead, the Wayland compositor sends a request to the client to resize to the new size. The client needs to submit a new buffer (which might not even have the requested size). So, when you set_geometry() or similar, the view does not really resize, it will resize when the client submits a new buffer.

There are two main ways to fix this issue. One of these is the transaction system sway and river use. They try to ensure every frame is perfect by waiting for all clients to resize and then updating the contents on the screen. This approach is a bit complicated, requires synchronizing the state, timeouts when a client is not responsive, etc. It might be possible to implement in Wayfire once https://github.com/WayfireWM/wayfire/issues/995 is done.

The another way is much more hacky, but IMO it works well enough in practice. The idea is to force the position of the views with a transformer (scaling and translating them), and then waiting for their size to change, in which case we just remove the transformers. This is what simple-tile does. https://github.com/WayfireWM/wayfire/blob/master/plugins/tile/tree.cpp#L261

I hope this answers your question.

**Comment by Javyre** [comment]
(woops just saw this after posting on discussion sorry)

This does answer my question yes, thanks for following up. As I see this solution is already planned for milestone 0.9 I have much less of an issue doing the "hacky" alternative.
