### ISSUE TITLE
core: Fullscreening views not picked up by GeoEnforcer

### ISSUE THREAD

**Issue by Javyre** [Javyre/swayfire#22]
Open a view. Fullscreen it with the WMActions plugin. The view is not resized but instead weirdly squished in place by the geoenforcer.

reported by @aruhier

**Comment by aruhier** [comment]
Thanks a lot!
Yes, now windows go in fullscreen, however I think there's also a handle to implement in swayfire-decorations to not show the decorations/windows borders (and padding) when a window is in fullscreen.

**Comment by Javyre** [comment]
Yeah that's NYI right now and on the todo for deco plugin. #23
