### ISSUE TITLE
Decorations: segfault when closing a window

### ISSUE THREAD

**Issue by aruhier** [Javyre/swayfire#29]
Wayfire segfaults a bit randomly when closing a window with Swayfire-decorations enabled: 

Log: [wayfire_segv.log](https://github.com/Javyre/swayfire/files/6635320/wayfire_segv.log)
Trace: [wayfire_strace.log](https://github.com/Javyre/swayfire/files/6635323/wayfire_strace.log)

### How to reproduce
After starting Wayfire, open 2 windows in tiled mode, close one of it, Wayfire crashes. Doing other actions like changing workspace seem to inhibit the issue.

**Comment by Javyre** [comment]
hmm I just reproduced this exactly how you described it but can't do it again.. Have you found any sort of pattern that would make this more reproducible?

**Comment by aruhier** [comment]
It is pretty weird and happens usually just after I start wayfire. So what I do is I start wayfire, quickly opens 2 terminal windows, close one though a binding, and it crashes.
