### ISSUE TITLE
shows meson.build:16:0: ERROR: Dependency "wayfire" not found, tried pkgconfig and cmake , even though wayfire is installed

### ISSUE THREAD

**Issue by Sam1431** [Javyre/swayfire#3]

**Comment by Sam1431** [comment]
I'm using void and would love to have this feature in wayfire , but the thing is it shows wayfire is not present during compile even if it is installed

**Comment by Javyre** [comment]
Hey, I'm using void as well and everything works for me.
Do you have both the `wayfire` and `wayfire-devel` packages installed?

**Comment by Sam1431** [comment]
oh yeah , now it works
