### ISSUE TITLE
deco: Implement "should corner be rounded" detection

### ISSUE THREAD

**Issue by Javyre** [Javyre/swayfire#35]
Currently, corner radii >0 are pretty ugly and useless since it is blindly applied to every corner. We need to detect whether a corner should be rounded or not so as to avoid "holes" as described in https://github.com/Javyre/swayfire/issues/19#issuecomment-847123760

**Comment by Javyre** [comment]
(test comment to see if irc bot works)

**Comment by Javyre** [comment]
(test comment to see if irc bot works)

**Comment by ErikReider** [comment]
So this should only round the outside corners (the corners closest to each display edge)?

**Comment by Javyre** [comment]
A setting could be added to round display-edge corners pretty easily, but for now it only rounds outer corners of floating nodes (either single floating views or whole floating tiling trees)

**Comment by ErikReider** [comment]
Oh. I read my comment again and it didn't really make any sense 😅. I was wondering if this PR only rounds the corners of tiled windows that are the closest to each corner of the display to remove the gap in between each window

**Comment by Javyre** [comment]
Oh I see. Yes exactly. Except that the main tiling tree (i.e. non-floating trees) aren't rounded at all. (this last part is what I was saying could be made configurable if there is demand)
